### Imprting Libraries

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [2]:
# Loading Datasett

df = pd.read_csv(r'C:\Users\R.VENKAT\Desktop\Python codes\DataSets\weatherAUS.csv')

### Exploratory Data Analysis

In [3]:
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,0.0,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,0.0,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,0.0,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,1.0,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,0.2,No

In [4]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 24 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  str
 1   Location       142193 non-null  str
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  str
 8   WindGustSpeed  132923 non-null  float64
 9   WindDir9am     132180 non-null  str
 10  WindDir3pm     138415 non-null  str
 11  WindSpeed9am   140845 non-null  float64
 12  WindSpeed3pm   139563 non-null  float64
 13  Humidity9am    140419 non-null  float64
 14  Humidity3pm    138583 non-null  float64
 15  Pressure9am    128179 non-null  float64
 16  Pressure3pm    128212 non-null  float64
 17  Cloud9am       88536 non-null   float64
 18  Cloud3pm       85099 non-null   float64
 19  Temp9am        141289 non-null  float64
 20  Temp3pm        139467 non-null  float64
 21  RainToday      140787 non-null  str
 22  RISK_MM        142193 non-null  float64
 23  RainTomorrow   142193 non-null  str
dtypes: float64(17), str(7)
memory usage: 30.1 MB

In [5]:
df.shape,df.size

((142193, 24), 3412632)

In [6]:
# Detecting Null Values
df.isnull().sum()

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [7]:
#Detecting Null Values percentage
df.isnull().sum()/len(df)*100

Date              0.000000
Location          0.000000
MinTemp           0.447983
MaxTemp           0.226453
Rainfall          0.988797
Evaporation      42.789026
Sunshine         47.692924
WindGustDir       6.561504
WindGustSpeed     6.519308
WindDir9am        7.041838
WindDir3pm        2.656952
WindSpeed9am      0.948007
WindSpeed3pm      1.849599
Humidity9am       1.247600
Humidity3pm       2.538803
Pressure9am       9.855619
Pressure3pm       9.832411
Cloud9am         37.735332
Cloud3pm         40.152469
Temp9am           0.635756
Temp3pm           1.917113
RainToday         0.988797
RISK_MM           0.000000
RainTomorrow      0.000000
dtype: float64

In [8]:
# Finding Duplicates

df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132923.000000,140845.000000,139563.000000,140419.000000,138583.000000,128179.000000,128212.000000,88536.000000,85099.000000,141289.000000,139467.000000,142193.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,39.984292,14.001988,18.637576,68.843810,51.482606,1017.653758,1015.258204,4.437189,4.503167,16.987509,21.687235,2.360682
std,6.403283,7.117618,8.465173,4.188537,3.781525,13.588801,8.893337,8.803345,19.051293,20.797772,7.105476,7.036677,2.887016,2.720633,6.492838,6.937594,8.477969
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.500000,977.100000,0.000000,0.000000,-7.200000,-5.400000,0.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,0.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,0.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,0.800000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.000000,1039.600000,9.000000,9.000000,40.200000,46.700000,371.000000

In [10]:
df.describe(include=str)

,Date,Location,WindGustDir,WindDir9am,WindDir3pm,RainToday,RainTomorrow
count,142193,142193,132863,132180,138415,140787,142193
unique,3436,49,16,16,16,2,2
top,2013-03-02,Canberra,W,N,SE,No,No
freq,49,3418,9780,11393,10663,109332,110316

### Preprocessing Of Data

In [11]:
numerical = df.describe().columns      # taking out the numerical columns separately
print(f"Numerical Columns : {numerical}\n")

category = df.describe(include=str).columns     # taking out the category columns
print(f"Category : {category}")

Numerical Columns : Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RISK_MM'],
      dtype='str')

Category : Index(['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm',
       'RainToday', 'RainTomorrow'],
      dtype='str')

In [12]:
# filling Null(Missing) values for numerical features with median

for col in numerical:
    med=df[col].median()
    df[col]=df[col].fillna(med)

In [23]:
# filling Null(Missing) values for category features with mode

df['RainToday'] = df['RainToday'].fillna('No')
df['WindDir9am'] = df['WindDir9am'].fillna('N')
df['WindDir3pm'] = df['WindDir3pm'].fillna('SE')
df['WindGustDir'] = df['WindGustDir'].fillna('W')

In [25]:
# date feature engineering

df['Date'] = pd.to_datetime(df['Date'])

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [26]:
df.drop(['Date'], inplace = True, axis =1)

In [28]:
df.drop(['RISK_MM'], inplace = True, axis =1)

In [29]:
df.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,Year,Month,Day
0,Albury,13.4,22.9,0.6,4.8,8.5,W,44.0,W,WNW,...,1007.1,8.0,5.0,16.9,21.8,No,No,2008,12,1
1,Albury,7.4,25.1,0.0,4.8,8.5,WNW,44.0,NNW,WSW,...,1007.8,5.0,5.0,17.2,24.3,No,No,2008,12,2
2,Albury,12.9,25.7,0.0,4.8,8.5,WSW,46.0,W,WSW,...,1008.7,5.0,2.0,21.0,23.2,No,No,2008,12,3
3,Albury,9.2,28.0,0.0,4.8,8.5,NE,24.0,SE,E,...,1012.8,5.0,5.0,18.1,26.5,No,No,2008,12,4
4,Albury,17.5,32.3,1.0,4.8,8.5,W,41.0,ENE,NW,...,1006.0,7.0,8.0,17.8,29.7,No,No,2008,12,5

In [30]:
# Spliting the data into output(y) and input(X)

X = df.drop('RainTomorrow', axis = 1)
y = df['RainTomorrow']

In [33]:
X_train, X_test, y_train, y_test = train_test_split( X, y , test_size = 0.3 , random_state = 21)

In [38]:
numerical = X_train.describe().columns

In [39]:
# One Hot Encoding on category columns

X_train = pd.concat([X_train[numerical],
                    pd.get_dummies(X_train['Location'], prefix ='Location', dtype = int),
                    pd.get_dummies(X_train['WindGustDir'], prefix = 'WindGustDir', dtype= int),
                    pd.get_dummies(X_train['WindDir9am'], prefix = 'WindDir9am', dtype =int),
                    pd.get_dummies(X_train['WindDir3pm'], prefix = 'WindDir3pm', dtype = int),
                    pd.get_dummies(X_train['RainToday'], prefix = 'RainToday', dtype = int)], axis =1)

In [41]:
X_test = pd.concat([X_test[numerical],
                    pd.get_dummies(X_test['Location'], prefix ='Location', dtype = int),
                    pd.get_dummies(X_test['WindGustDir'], prefix = 'WindGustDir', dtype= int),
                    pd.get_dummies(X_test['WindDir9am'], prefix = 'WindDir9am', dtype =int),
                    pd.get_dummies(X_test['WindDir3pm'], prefix = 'WindDir3pm', dtype = int),
                    pd.get_dummies(X_test['RainToday'], prefix = 'RainToday', dtype = int)], axis =1)

### Creating Random Forest Model

In [62]:
model = RandomForestClassifier(n_estimators = 150, max_depth= 15, random_state = 28)

In [63]:
model.fit(X_train,y_train)

RandomForestClassifier(max_depth=15, n_estimators=150, random_state=28)

In [64]:
y_pred= model.predict(X_test)

In [65]:
# Evaluation

accuracy_score(y_test,y_pred)

0.8500867363683248

In [66]:
from sklearn.metrics import classification_report

In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.86      0.96      0.91     33138
         Yes       0.78      0.45      0.57      9520

    accuracy                           0.85     42658
   macro avg       0.82      0.71      0.74     42658
weighted avg       0.84      0.85      0.83     42658

In [53]:
# Handling Imbalance Data

from imblearn.over_sampling import SMOTE

In [54]:
smote = SMOTE(random_state = 23)

In [56]:
X_train_S, y_train_S = smote.fit_resample(X_train,y_train)

In [68]:
model_S = RandomForestClassifier( n_estimators = 150 , max_depth = 20 , random_state= 25)

In [69]:
model_S.fit(X_train_S, y_train_S)

RandomForestClassifier(max_depth=20, n_estimators=150, random_state=25)

In [70]:
y_pred_S = model_S.predict(X_test)

In [71]:
accuracy_score(y_test, y_pred_S)

0.8419757138168691

In [72]:
print(classification_report(y_test, y_pred_S))

              precision    recall  f1-score   support

          No       0.90      0.90      0.90     33138
         Yes       0.64      0.65      0.65      9520

    accuracy                           0.84     42658
   macro avg       0.77      0.77      0.77     42658
weighted avg       0.84      0.84      0.84     42658